- hosts: ubuntu
  vars_files:
    - configs/vars.yaml
  tasks:
  - name: 'create link'
    become: yes
    file:
      src: "{{ nginx_sites_available }}"
      dest: "{{ nginx_sites_enabled }}"
      state: link
  - name: 'restart nginx'
    become: yes
    service: 
      name: nginx
      state: restarted
      enabled: true
  - name: 'Check if wordpress file exist'
    stat: path=/var/www/wordpress
    register: check_path
  - name: 'Download wordpress files'
    get_url:
      url: "{{ wordpress_remote_site_path }}" 
      dest: "{{ wordpress_local_site_path }}"
    when: not check_path.stat.exists
  - name: 'Extract files'
    unarchive:
      src: "{{ wordpress_local_site_path }}"
      dest: "{{ nginx_www }}"
      remote_src: yes
    become: yes
    when: not check_path.stat.exists
  - name: 'Change ownership of file wordpress'
    file:
      path: /var/www/wordpress
      owner: www-data
      group: www-data
    become: yes
