- hosts: ubuntu
  vars:
    mysql_root_password: 19981120
    db_name: wordpress_db
    db_username: wordpress_user
    db_user_pass: my_password
  tasks:
  - name: Install all required packages
    apt: 
      name:
        - mariadb-server
        - python3-pip
        - nginx
        - mariadb-client
        - php-fpm
        - php-mysql
      update_cache: yes
      cache_valid_time: 3600
      state: present
    become: yes
  - name: Start the MySQL service
    become: yes
    service: 
      name: mariadb 
      state: started
      enabled: true
  - name: "Install pymysql module"
    become: yes
    command: "pip3 install PyMySQL"

  - name: update mysql root password for all root accounts
    become: yes
    mysql_user: 
      name: root 
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
      login_unix_socket: /var/run/mysqld/mysqld.sock
  - name: 'create mysql user'
    mysql_user:
      name: '{{ db_username }}'
      password: '{{ db_user_pass }}'
      priv: '*.*:ALL'
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    become: yes
  - name: 'create mysql db'
    mysql_db:
      name: '{{ db_name }}'
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    become: yes
  - name: 'Send configuration file'
    copy:
      src: configs/wordpress_nginx
      dest: /etc/nginx/sites-available/wordpress_nginx
    become: yes
  - name: 'Change hostname in config file'
    replace:
      path: /etc/nginx/sites-available/wordpress_nginx
      regexp: '127.0.0.1'
      replace: "{{ ansible_host }}"
    become: yes
  - name: 'remove default nginx config'
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    become: yes
  - name: 'create link'
    become: yes
    file:
      src: /etc/nginx/sites-available/wordpress_nginx
      dest: /etc/nginx/sites-enabled/wordpress_nginx
      state: link
  - name: 'restart nginx'
    become: yes
    service: 
      name: nginx
      state: restarted
      enabled: true
 
