- hosts: ubuntu
  vars_files:
    - configs/vars.yaml
  tasks:
  - name: Install all required packages
    apt: 
      name:
        - mariadb-server
        - python3-pip
        - nginx
        - mariadb-client
        - php-fpm
        - php-mysql
      update_cache: yes
      cache_valid_time: 3600
      state: present
    become: yes
  - name: Start the MySQL service
    become: yes
    service: 
      name: mariadb 
      state: started
      enabled: true
  - name: "Install pymysql module"
    become: yes
    command: "pip3 install PyMySQL"
  - name: update mysql root password for all root accounts
    become: yes
    mysql_user: 
      name: "{{ mysql_root_user }}" 
      password: "{{ mysql_root_password }}"
      login_user: "{{ mysql_root_user }}"
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
      login_unix_socket: "{{ mysql_socket }}"
  - name: 'create mysql user'
    mysql_user:
      name: '{{ db_username }}'
      password: '{{ db_user_pass }}'
      priv: '*.*:ALL'
      login_user: "{{ mysql_root_user }}"
      login_password: "{{ mysql_root_password }}"
      login_unix_socket: "{{ mysql_socket }}"
    become: yes
  - name: 'create mysql db'
    mysql_db:
      name: '{{ db_name }}'
      state: present
      login_user: "{{ mysql_root_user }}"
      login_password: "{{ mysql_root_password }}"
      login_unix_socket: "{{ mysql_socket }}"
    become: yes
  - name: 'Send configuration file'
    copy:
      src: "{{ wordpress_config_path }}"
      dest: "{{ nginx_sites_available }}"
    become: yes
  - name: 'Change hostname in config file'
    replace:
      path: "{{ nginx_sites_available }}"
      regexp: '127.0.0.1'
      replace: "{{ ansible_host }}"
    become: yes
  - name: 'remove default nginx config'
    file:
      path: "{{ nginx_default_path }}"
      state: absent
    become: yes
  - name: 'create link'
    become: yes
    file:
      src: "{{ nginx_sites_available }}"
      dest: "{{ nginx_sites_enabled }}"
      state: link
  - name: 'restart nginx'
    become: yes
    service: 
      name: nginx
      state: restarted
      enabled: true
  - name: 'Check if wordpress file exist'
    stat: path=/var/www/wordpress
    register: check_path
  - name: 'Download wordpress files'
    get_url:
      url: "{{ wordpress_remote_site_path }}" 
      dest: "{{ wordpress_local_site_path }}"
    when: not check_path.stat.exists
  - name: 'Extract files'
    unarchive:
      src: "{{ wordpress_local_site_path }}"
      dest: "{{ nginx_www }}"
      remote_src: yes
    become: yes
    when: not check_path.stat.exists
  - name: 'Change ownership of file wordpress'
    file:
      path: /var/www/wordpress
      owner: www-data
      group: www-data
    become: yes
