ansible_sudo_pass: 19981120
mysql_root_user: root
mysql_root_password: 19981120

db_name: wordpress_db
db_username: wordpress_user
db_user_pass: my_password

mysql_socket: /var/run/mysqld/mysqld.sock

wordpress_config_path: configs/wordpress_nginx
wordpress_remote_site_path: https://wordpress.org/latest.tar.gz 
wordpress_local_site_path: /tmp/wordpress.tar.gz
nginx_www: /var/www
nginx_sites_available: /etc/nginx/sites-available/wordpress_nginx
nginx_sites_enabled: /etc/nginx/sites-enabled/wordpress_nginx
nginx_default_path: /etc/nginx/sites-enabled/default
